---
# check for not specified variables from group_vars/all.yml

- fail:
    msg: "contrail_ip: Please check group_vars/all.yml if all required vars were set."
  when: not contrail_ip | ipv4 
  tags: check

- fail:
    msg: "openstack_ip: Please check group_vars/all.yml if all required vars were set."
  when: not openstack_ip | ipv4
  tags: check

- fail:
    msg: "openstack_branch: Please check group_vars/all.yml if all required vars were set."
  when: not openstack_branch | mandatory
  tags: check

- fail:
    msg: "contrail_branch: Please check group_vars/all.yml if all required vars were set."
  when: not contrail_branch | mandatory
  tags: check

- fail:
    msg: "kernel_version: Please check group_vars/all.yml if all required vars were set."
  when: not kernel_version | mandatory
  tags: check
