---
# install required dependencies 
- name: install python-apt
  command: apt install {{ item }} -y 
  with_items:
    - "python-apt"
    - "libsasl2-dev"
  become: yes

- name: install git, pip, setuptools & python-dev
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "git"
    - "python-setuptools"
    - "python-pip"
    - "python-dev"
  become: yes

- name: (hack) install devstack dependencies those will be replaced later with devstack requirements.txt
  pip: 
    name: "{{ item }}"
  become: yes
  with_items:
    - 'pytz'
    - 'iso8601'
    - 'cmd2'
    - 'netifaces'
    - 'monotonic'
    - 'wrapt'
    - 'rfc3986'
