---
# Add hostname to /etc/hosts

- name: adding hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ ansible_hostname }}'
    state: present
  become: yes
