---
# install prerequisite for xenial

- name: setup nameserver before installing python
  raw: 'sed -i_bak "s/\(nameserver\) .*/\1 8\.8\.8\.8/" /etc/resolv.conf'
  become: yes

- name: install python 2.7 required by ansible 
  raw: 'apt-get update && apt install -y python'
  become: yes
