- project:
    name: openstack/networking-opencontrail
    check:
      jobs:
        - contrail-integration-ocata
        - contrail-integration-base:
            voting: false
        - noc-tempest-ocata
        - noc-tempest-base:
            voting: false
    gate:
      jobs:
        - contrail-integration-base
        - noc-tempest-ocata
    periodic:
      jobs:
        - contrail-integration-base:
            branches:
              - master
              - ^stable/[a-z]+$

- job:
    name: noc-tempest-base
    parent: devstack-tempest
    description: Base job for tempest-based tests
    required-projects:
      - openstack/neutron-tempest-plugin
      - openstack/networking-opencontrail
    roles:
      - zuul: openstack-dev/devstack
    timeoute: 9000
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        networking-opencontrail: git://git.openstack.org/openstack/networking-opencontrail
        neutron-tempest-plugin: git://git.openstack.org/openstack/neutron-tempest-plugin
      tempest_test_regex: tempest\.(api|scenario|thirdparty)|neutron_tempest_plugin
      devstack_localrc:
        ADMIN_PASSWORD: admin
        HOST_IP: "{{hostvars['controller'].ansible_default_ipv4.address}}"
        OPENCONTRAIL_APISERVER_IP: "{{hostvars['controller'].ansible_default_ipv4.address}}"
        OPENCONTRAIL_APISERVER_PORT: 8082
        Q_USE_SECGROUP: True
        Q_PLUGIN: ml2
        ML2_L3_PLUGIN: opencontrail-router
      devstack_local_conf:
        post-config:
          $NEUTRON_CORE_PLUGIN_CONF:
            ml2:
              type_drivers: local,flat,vlan,gre,vxlan,geneve
              tenant_network_types: vlan
              extension_drivers: port_security
              mechanism_drivers: opencontrail,openvswitch,linuxbridge
            ml2_type_vlan:
              network_vlan_ranges: public:1:1000
            ml2_type_vxlan:
              vni_ranges: 1:1000
            ml2_type_gre:
              tunnel_id_ranges: 1:1000

- job:
    name: noc-tempest-ocata
    parent: noc-tempest-base
    override-checkout: stable/ocata
    devstack_plugins:
      networking-opencontrail: git://git.openstack.org/openstack/networking-opencontrail stable/ocata
      neutron-tempest-plugin: git://git.openstack.org/openstack/neutron-tempest-plugin

- job:
    name: contrail-integration-base
    parent: devstack-platform-centos-7
    description: |
      Integration tests between devstack and opencontrail
      using openstack/networking-opencontrail neutron plugin
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-opencontrail
    timeout: 10800
    roles:
      - zuul: openstack-dev/run-devstack
    pre-run: zuul-playbooks/pre.yaml
    run: zuul-playbooks/run.yaml
    post-run: zuul-playbooks/post.yaml
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        networking-opencontrail: git://git.openstack.org/openstack/networking-opencontrail
      devstack_localrc:
        ADMIN_PASSWORD: admin
        HOST_IP: "{{hostvars['controller'].ansible_default_ipv4.address}}"
        OPENCONTRAIL_APISERVER_IP: "{{hostvars['controller'].ansible_default_ipv4.address}}"
        OPENCONTRAIL_APISERVER_PORT: 8082
        Q_USE_SECGROUP: True
        Q_PLUGIN: ml2
        ML2_L3_PLUGIN: opencontrail-router
        NEUTRON_CREATE_INITIAL_NETWORKS: False
      devstack_local_conf:
        post-config:
          $NEUTRON_CORE_PLUGIN_CONF:
            ml2:
              type_drivers: local,flat,vlan,gre,vxlan,geneve
              tenant_network_types: vlan
              extension_drivers: port_security
              mechanism_drivers: opencontrail,openvswitch,linuxbridge
            ml2_type_vlan:
              network_vlan_ranges: public:1:1000
            ml2_type_vxlan:
              vni_ranges: 1:1000
            ml2_type_gre:
              tunnel_id_ranges: 1:1000

- job:
    name: contrail-integration-ocata
    parent: contrail-integration-base
    override-checkout: stable/ocata
    vars:
      devstack_plugins:
        networking-opencontrail: git://git.openstack.org/openstack/networking-opencontrail stable/ocata
