- project:
    check:
      jobs:
        - contrail-integration

- nodeset:
    name: centos-7-ubuntu
    nodes:
      - name: primary
        label: ubuntu-xenial
      - name: contrail
        label: centos-7

- job:
    voting: false
    name: contrail-integration
    parent: legacy-dsvm-base
    timeout: 10800
    nodeset: centos-7-ubuntu
    required-projects:
      - openstack-infra/devstack-gate
    pre-run: zuul-playbooks/pre.yaml
    run: zuul-playbooks/run.yaml

