- project:
    check:
      jobs:
        - contrail-integration
    gate:
      jobs:
        - contrail-integration

- nodeset:
    name: centos-7-ubuntu
    nodes:
      - name: controller
        label: ubuntu-xenial
      - name: contrail
        label: centos-7

- job:
    voting: false
    name: contrail-integration
    parent: devstack-tempest
    timeout: 10800
    nodeset: centos-7-ubuntu
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-opencontrail
    pre-run: zuul-playbooks/pre.yaml
    run: zuul-playbooks/run.yaml
    post-run: zuul-playbooks/post.yaml
    vars:
      devstack_plugins:
        networking-opencontrail: 'git://git.openstack.org/openstack/networking-opencontrail'
      devstack_localrc:
        OPENCONTRAIL_APISERVER_IP: "'{{hostvars['contrail'].ansible_default_ipv4.address}}'"
        OPENCONTRAIL_APISERVER_PORT: 8082
        Q_USE_SECGROUP: True
        Q_PLUGIN: ml2
        ML2_L3_PLUGIN: opencontrail-router
        NEUTRON_CREATE_INITIAL_NETWORKS: False

