- project:
    name: openstack/networking-opencontrail
    check:
      jobs:
        - noc-integration:
            voting: false
        - noc-tempest:
            voting: false
    gate:
      jobs:
        - noc-integration
        - noc-tempest
    periodic:
      jobs:
        - noc-integration:
            branches:
              - master
              - ^stable/[a-z]+$
        - noc-tempest:
            branches:
              - master
              - ^stable/[a-z]+$

- job:
    name: noc-base
    parent: devstack-tempest
    description: Networking-OpenContrail base job
    post-run: playbooks/zuul/post.yaml
    nodeset: devstack-single-node-centos-7
    roles:
      - zuul: openstack-dev/devstack
    timeout: 9200
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/tempest
      - openstack/neutron-tempest-plugin
      - openstack/networking-opencontrail
      - openstack/glance
      - openstack/keystone
      - openstack/neutron
      - openstack/nova
    vars:
      devstack_base_dir: /opt/stack
      devstack_localrc:
        DEBUG: True
        ADMIN_PASSWORD: admin
        HOST_IP: "{{hostvars['controller'].ansible_default_ipv4.address}}"
        OPENCONTRAIL_APISERVER_IP: "{{hostvars['controller'].ansible_default_ipv4.address}}"
        OPENCONTRAIL_APISERVER_PORT: 8082
        Q_USE_SECGROUP: True
        Q_PLUGIN: ml2
        ML2_L3_PLUGIN: opencontrail-router
        NEUTRON_CREATE_INITIAL_NETWORKS: False
        PUBLIC_PHYSICAL_NETWORK: public
        USE_SSL: False
      devstack_services:
        # Shared services
        dstat: true
        etcd3: true
        mysql: true
        peakmem_tracker: true
        rabbit: true
        tls-proxy: false
        # Keystone services
        key: true
        # Glance services
        g-api: true
        g-reg: true
        # Nova services
        n-api: true
        n-api-meta: true
        n-cauth: true
        n-cond: true
        n-cpu: true
        n-novnc: true
        n-obj: true
        n-sch: true
        placement-api: true
        # Neutron services
        # We need to keep using the neutron-legacy based services for
        # now until all issues with the new lib/neutron code are solved
        q-agt: true
        q-dhcp: true
        q-l3: true
        q-meta: true
        q-metering: true
        q-svc: true
        # neutron-api: true
        # neutron-agent: true
        # neutron-dhcp: true
        # neutron-l3: true
        # neutron-metadata-agent: true
        # neutron-metering: true
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Services we don't need.
        # This section is not really needed, it's for readability.
        horizon: false
        tempest: true
      devstack_local_conf:
        post-config:
          $NEUTRON_CORE_PLUGIN_CONF:
            ml2:
              type_drivers: vlan,vxlan
              tenant_network_types: vlan,vxlan
              extension_drivers: port_security
              mechanism_drivers: opencontrail,openvswitch,linuxbridge
            ml2_type_vlan:
              network_vlan_ranges: public:1:1000
            ml2_type_vxlan:
              vni_ranges: 1:1000

- job:
    name: noc-tempest
    parent: noc-base
    description: Neutron tempest tests
    run: playbooks/zuul/noc-tempest.yaml
    vars:
      devstack_plugins:
        networking-opencontrail: git://git.openstack.org/openstack/networking-opencontrail
        neutron-tempest-plugin: git://git.openstack.org/openstack/neutron-tempest-plugin

- job:
    name: noc-integration
    parent: noc-base
    description: Integration tests between devstack and opencontrail
    run: playbooks/zuul/noc-integration.yaml
    vars:
      devstack_plugins:
        networking-opencontrail: git://git.openstack.org/openstack/networking-opencontrail
