- project:
    check:
      jobs:
        - contrail-integration
    gate:
      jobs:
        - contrail-integration

- nodeset:
    name: centos-7-ubuntu
    nodes:
      - name: controller
        label: ubuntu-xenial
      - name: contrail
        label: centos-7

- job:
    voting: false
    name: contrail-integration
    parent: devstack-tempest
    timeout: 1080
    nodeset: centos-7-ubuntu
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-opencontrail
    pre-run: zuul-playbooks/pre.yaml
    #run: zuul-playbooks/run.yaml

