---
# Copy ContrailMechanismDriver dependencies from Contrail VM
- name: create archive for vnc_api module
  command: chdir=/opt/stack/contrail/build/production/api-lib python setup.py sdist
  become: yes
  tags: driver
 
- name: create archive for cfgm_common module
  command: chdir=/opt/stack/contrail/build/production/config/common python setup.py sdist
  become: yes
  tags: driver

- name: fetch vnc_api && cfgm_common module
  run_once: yes
  fetch:
    src: /opt/stack/contrail/build/production/{{ item }}
    dest: /tmp/
    flat: yes
  with_items:
    - 'api-lib/dist/vnc_api-0.1.dev0.tar.gz'
    - 'config/common/dist/cfgm_common-0.1.dev0.tar.gz'
  tags: driver
