---
# source openrc in bash profile
- name: source openrc in profile
  lineinfile: 
    dest: ~/.profile 
    regexp: ".*openrc" 
    line: ". ~/devstack/openrc"
    state: present

- name: source openrc in current shell
  shell: . ~/devstack/openrc
