# This is taken from https://github.com/openstack/tempest/blob/7541031d1742f31b467134816202485d5a630e05/playbooks/devstack-tempest.yaml
# TODO(paweł_zadrożny): Ideally we want to use their run playbook but until https://review.openstack.org/#/c/530642/ is resolved.

# Changes that run through devstack-tempest are likely to have an impact on
# the devstack part of the job, so we keep devstack in the main play to
# avoid zuul retrying on legitimate failures.
# We run tests only on one node, regardless how many nodes are in the system
- hosts: controller
  roles:
    - run-devstack
    - run-contrail
    - setup-tempest-run-dir
    - setup-tempest-data-dir
    - acl-devstack-files
    - run-tempest
  tasks:
    - name: Pause execution to make sure workers flushed all logs before stoping
      pause:
        seconds: 30
