- hosts: all
  roles:
    - role: export-devstack-journal
      ignore_errors: yes
    - role: devstack-project-conf
      ignore_errors: yes
    - role: capture-system-logs
      ignore_errors: yes
    - role: fetch-devstack-log-dir
      ignore_errors: yes

- hosts: controller
  tasks:
    - name: Copy contrail logs
      become: yes
      synchronize:
        src: "/var/log/contrail"
        dest: "{{ zuul.executor.log_root }}/controller/logs"
        mode: pull

    - name: Copy contrail-ansible-deployer config files
      become: yes
      synchronize:
        src: "/home/zuul/contrail-ansible-deployer/{{ item }}"
        dest: "{{ zuul.executor.log_root }}/controller/logs/contrail/{{ item }}"
        mode: pull
        recursive: yes
      with_items:
        - "config"
        - "inventory"

    - name: Save list of running containers
      become: yes
      shell: |
        set -e
        set -x
        docker ps --format={% raw %}'{{.Names}}: {{.Status}}'{% endraw %} | tee /etc/docker/running_containers.txt

    - name: Copy docker files
      become: yes
      synchronize:
        src: "/etc/docker"
        dest: "{{ zuul.executor.log_root }}/controller/logs"
        mode: pull
