---
# Copy Contrail libs to Openstack VM and install them

- name: copy vnc_api && cfgm_common module
  copy:
    src: /tmp/{{ item }}
    dest: ~/devstack
  with_items:
    - 'vnc_api-0.1.dev0.tar.gz'
    - 'cfgm_common-0.1.dev0.tar.gz'
  tags: driver
 
- name: install vnc_api && cfgm_common module
  shell: 'cd ~/devstack && sudo pip install {{ item }}'
  with_items:
    - 'vnc_api-0.1.dev0.tar.gz'
    - 'cfgm_common-0.1.dev0.tar.gz'
  tags: driver

- name: clone contrail-neutron-plugin to satisfy dependencies
  git: 
    repo: "https://github.com/Juniper/contrail-neutron-plugin.git"
    dest: ~/contrail-neutron-plugin 
    accept_hostkey: yes
  tags: driver

- name: install contrail-neutron-plugin
  shell: sudo pip install .
  args:
    chdir: ~/contrail-neutron-plugin
  tags: driver
