---
# Patch stack.sh for proper endpoints used by OpenContrail controller
- name: copy Openstack endpoint patch
  copy:
    src: "{{ item }}"
    dest: ~/devstack/keystone.patch
  with_first_found:
    - ../files/keystone_{{ openstack_branch | regex_replace('/', '-') }}.patch
    - ../files/keystone.patch

- name: patch keystone endpoint 
  shell: patch keystone < ../keystone.patch
  args:
    chdir: ~/devstack/lib
