---
# Patch stack.sh for proper endpoints used by OpenContrail controller
- name: copy Openstack endpoint patch
  copy:
    src: ../files/keystone.patch
    dest: ~/devstack/keystone.patch

- name: patch keystone endpoint 
  shell: patch keystone < ../keystone.patch
  args:
    chdir: ~/devstack/lib
