---
# Install Contrail (with use of devstack), do not enable any services yet

- hosts: contrail
  gather_facts: no 
  become: no
  roles:
    - { role: fetch_devstack, vm_group: contrail }
    - { role: contrail_vm }

