#!/usr/bin/env ansible-playbook

- hosts: controller
  roles:
    - devstack_controller_node
    - restack_controller_node
- hosts: compute
  roles:
    - contrail_node
- hosts: controller
  roles:
    - { role: networking_bgpvpn_plugin, when: install_networking_bgpvpn_plugin }
    - { role: restack_controller_node, when: install_networking_bgpvpn_plugin }
- hosts: compute
  roles:
    - devstack_compute_node
    - restack_compute_node
