#!/usr/bin/env ansible-playbook

- include: change_password.yml
- include: fix_docker_bip.yml
- include: main.yml
- hosts: controller
  tasks:
  - name: Restart horizon
    become: yes
    shell: systemctl restart httpd
  - name: Restart contrail
    shell: docker restart config_api_1
  - name: Wait for Contrail API to come up
    uri:
      url: "http://{{ hostvars['controller'].ansible_default_ipv4.address }}:8082/projects"
      status_code:
      - 200
      - 304
      validate_certs: no
    register: result
    until: result.status == 200 or result.status == 304
    retries: 30
    delay: 5
  - name: synchronize projects
    shell: |
      source ~/devstack/openrc admin admin
      echo "{{ hostvars['compute'].ansible_default_ipv4.address }}"
      openstack project list -c ID -f csv | tail -n +2 | python -c 'import sys,uuid; print "\n".join([str(uuid.UUID(proj_id.strip().strip("\""))) for proj_id in sys.stdin])' | xargs -I PROJ_ID curl {{ hostvars[groups['compute'][0]].groups.compute[0] }}:8082/project/PROJ_ID
