---
# Install OpenStack (via devstack)

- hosts: openstack 
  gather_facts: no 
  become: no
  roles:
    - { role: fetch_devstack, vm_group: openstack }
    - { role: openstack_vm }
    - { role: source_openrc }

