#!/usr/bin/env ansible-playbook

- hosts: controller
  roles:
    - devstack_controller_node
    - restack_controller_node
- hosts: contrail_controller
  roles:
    - contrail_node
- hosts: controller
  roles:
    - { role: networking_bgpvpn_plugin, when: install_networking_bgpvpn_plugin }
    - { role: restack_controller_node, when: install_networking_bgpvpn_plugin }
- hosts: compute
  vars:
    separate_nodes: "{{ hostvars['controller'].ansible_host not in groups['compute'] }}"
  roles:
  - { role: devstack_compute_node, when: separate_nodes }
  - { role: restack_compute_node, when: separate_nodes }
