---
- hosts: controller
  tasks:
    - name: create resources
      args:
        executable: /bin/bash
      shell: |
        source ~/devstack/openrc admin demo
        openstack network create --provider-network-type vlan --provider-segment 3 --provider-physical-network public net
        openstack security group create secgroup
        openstack security group rule create --ingress --protocol icmp secgroup
        openstack security group rule create --ingress --protocol tcp secgroup
        openstack subnet create --network net --subnet-range 192.168.1.0/24 --dhcp subnet
        openstack server create  --flavor cirros256 --image cirros-0.3.5-x86_64-disk --nic net-id=net --security-group secgroup instance


        source ~/devstack/openrc admin demo
        openstack network create --provider-network-type vlan --provider-segment 30 --provider-physical-network public net

        # openstack security group create secgroup
        # openstack security group rule create --ingress --protocol icmp secgroup
        # openstack security group rule create --ingress --protocol tcp secgroup

        openstack subnet create --network net --subnet-range 192.168.10.0/24 --dhcp --allocation-pool start=192.168.10.3,end=192.168.10.254 subnet
        openstack server create  --flavor cirros256 --image cirros-0.3.5-x86_64-disk --nic net-id=net --security-group xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx instance
