---
# setup local.conf for restacking 
- name: uncomment n-cpu & placement-api (if needed)
  lineinfile:
    dest: ~/devstack/local.conf 
    regexp: (?i)^\s*#\s*({{ item }}.*)
    line: \1
    backrefs: yes
  with_items:
    - 'ENABLED_SERVICES' 
